using System.Collections.Generic;

/*
***************************************************************
*** NOTICE TO TRANSLATORS: DO NOT EDIT THIS FILE DIRECTLY! ***

We have provided a standard PO file to translation in /scripts/languages/strings.po
To add a new language:
- User a PO editor such as POEdit (http://www.poedit.net/) to translate strings.po
- Load your own PO file under /scripts/languages/language.lua

***************************************************************
*/
namespace DYT
{
    public class STRINGS
    {
        // ACTION MOUSEOVER TEXT
        public class ACTIONS
        {
            public static string
                TRAVEL = "Travel",
                BUNDLE = "Use",
                BUNDLESTORE = "Store",
                GNAW = "Gnaw",
                READ = "Read",
                READMAP = "Read",
                MAKEBALLOON = "Inflate",
                SEW = "Sew";
        }
    
        public static string
            MYSTERIOUS = "Peculiar",
            WITHEREDITEM = "Withered",
            SMOLDERINGITEM = "Smoldering",
            FLOODEDITEM = "Flooded",

            BLUEPRINT_ITEM = "%s Blueprint";
    
        public class WET_PREFIX
        {
            public static string
                NONE = "",
                GENERIC = "Wet",
                RABBITHOLE = "Collapsed",
                CLOTHING = "Soaked",
                FUEL = "Water-Logged",
                TOOL = "Slippery",
                FOOD = "Soggy",
                WETGOOP = "Very";
        }
    
        public class NAMES
        {
            public static string
                BUTTERFLYMUFFIN = "Butter Muffin",
                FROGGLEBUNWICH = "Froggle Bunwich",
                HONEYHAM = "Honey Ham",
                DRAGONPIE = "Dragonpie",
                TAFFY = "Taffy",
                PUMPKINCOOKIE = "Pumpkin Cookies",
                KABOBS = "Kabobs",
                MANDRAKESOUP = "Mandrake Soup",
                BACONEGGS = "Bacon and Eggs",
                BONESTEW = "Meaty Stew",
                PEROGIES = "Pierogi",
                WETGOOP = "Wet Goop",
                RATATOUILLE = "Ratatouille",
                FRUITMEDLEY = "Fruit Medley",
                FISHTACOS = "Fish Tacos",
                WAFFLES = "Waffles",
                TURKEYDINNER = "Turkey Dinner",
                DRUMSTICK = "Drumstick",
                DRUMSTICK_COOKED = "Fried Drumstick",
                TENTACLESPOTS = "Tentacle Spots",
                PERD = "Gobbler",
                ABIGAIL = "Abigail",
                MINERHAT = "Miner Hat",
                FISHSTICKS = "Fishsticks",
                STUFFEDEGGPLANT = "Stuffed Eggplant",
                HONEYNUGGETS = "Honey Nuggets",
                MEATBALLS = "Meatballs",
                JAMMYPRESERVES = "Fist Full of Jam",
                MONSTERLASAGNA = "Monster Lasagna",
                FLOWERSALAD = "Flower Salad",
                ICECREAM = "Ice Cream",
                WATERMELONICLE = "Melonsicle",
                TRAILMIX = "Trail Mix",
                HOTCHILI = "Spicy Chili",
                GUACAMOLE = "Guacamole",
                SPIDERHAT = "Spiderhat",
                WORMHOLE = "Worm Hole",
                WORMHOLE_LIMITED_1 = "Sick Worm Hole",

                FOOTBALLHAT = "Football Helmet",
                PIGSKIN = "Pig Skin",
                AXE = "Axe",
                HAMMER = "Hammer",
                GOLDENAXE = "Luxury Axe",
                MEAT = "Meat",
                COOKEDMEAT = "Cooked Meat",
                MEAT_DRIED = "Jerky",
                SMALLMEAT = "Morsel",
                COOKEDSMALLMEAT = "Cooked Morsel",
                SMALLMEAT_DRIED = "Small Jerky",
                MONSTERMEAT = "Monster Meat",
                COOKEDMONSTERMEAT = "Cooked Monster Meat",
                MONSTERMEAT_DRIED = "Monster Jerky",
                PLANTMEAT = "Leafy Meat",
                PLANTMEAT_COOKED = "Cooked Leafy Meat",
                TRAP = "Trap",
                LOG = "Log",
                HAMBAT = "Ham Bat",
                LIVINGLOG = "Living Log",
                TWIGS = "Twigs",
                CUTGRASS = "Cut Grass",
                PETALS = "Petals",
                PETALS_EVIL = "Dark Petals",
                ADVENTURE_PORTAL = "Maxwell's Door",
                POOP = "Manure",
                TORCH = "Torch",
                SEEDS = "Seeds",
                HOUND = "Hound",
                FIREHOUND = "Red Hound",
                SEEDS_COOKED = "Toasted Seeds",
                SILK = "Silk",
                SPIDERGLAND = "Spider Gland",
                TRAP_TEETH = "Tooth Trap",
                TRAP_TEETH_MAXWELL = "Maxwell's Tooth Trap",
                KRAMPUS = "Krampus",
                ROCK_LIGHT = "Lava Pit",
                ROCKS = "Rocks",
                ICE = "Ice",
                FLINT = "Flint",
                AMULET = "Life Giving Amulet",
                BLUEAMULET = "Chilled Amulet",
                PURPLEAMULET = "Nightmare Amulet",
                YELLOWAMULET = "Magiluminescence",
                ORANGEAMULET = "The Lazy Forager",
                GREENAMULET = "Construction Amulet",
                PICKAXE = "Pickaxe",
                GOLDENPICKAXE = "Opulent Pickaxe",
                SHOVEL = "Shovel",
                GOLDENSHOVEL = "Regal Shovel",
                PITCHFORK = "Pitchfork",
                GOLDENPITCHFORK = "Snazzy Pitchfork",
                BEEFALO = "Beefalo",
                BABYBEEFALO = "Baby Beefalo",
                BERRYBUSH = "Berry Bush",
                BERRYBUSH2 = "Berry Bush",
                SUNKBOAT = "Boat",
                BONFIRE = "Bonfire",
                CAMPFIRE = "Campfire",
                CROW = "Crow",
                ROBIN = "Redbird",
                ROBIN_WINTER = "Snowbird",
                EVERGREEN = "Evergreen",
                EVERGREEN_SPARSE = "Lumpy Evergreen",
                SLOW_FARMPLOT = "Basic Farm",
                FAST_FARMPLOT = "Improved Farm",
                FIRE = "Fire",
                COLDFIRE = "Endothermic Fire",
                COLDFIREPIT = "Endothermic Fire Pit",
                FIREPIT = "Fire Pit",
                HEATROCK = "Thermal Stone",
                FLOWER = "Flower",
                FLOWER_EVIL = "Evil Flower",
                FIREFLIES = "Fireflies",
                GHOST = "Ghost",
                GHOST_SAILOR = "Sailor's Ghost",
                GRASS = "Grass",
                DEPLETED_GRASS = "Grass",
                GRAVESTONE = "Headstone",
                INVENTORYGRAVE = "Headstone",
                INVENTORYMOUND = "Grave",
                HOMESIGN = "Sign",
                MAXWELL = "Maxwell",
                MOUND = "Grave",
                PIGHOUSE = "Pig House",
                PIGHOUSE_DOOR = "House With Door",
                PIGMAN = "Pig Man",
                CROP = "Crop",
                POND = "Pond",
                POND_MOS = "Pond",
                POND_CAVE = "Pond",
                RABBIT = "Rabbit",
                RABBITHOLE = "Rabbit Hole",
                ROCK1 = "Boulder",
                ROCK2 = "Boulder",
                ROCK_FLINTLESS = "Boulder",
                ROCK_ICE = "Mini Glacier",
                ROCK_ICE_MELTED = "Melted Mini Glacier",
                INSANITYROCK = "Obelisk",
                SANITYROCK = "Obelisk",
                SKELETON = "Skeleton",
                SKELETON_PLAYER = "Skeleton",
                PIGHEAD = "Pig Head",
                MERMHEAD = "Merm Head";
        }
    
        public static Dictionary<string, string> CHARACTER_TITLES = new Dictionary<string, string>
        {
            {"wilson", "The Gentleman Scientist"},
            {"willow", "The Firestarter"},
            {"wendy", "The Bereaved"},
            {"woodie", "The Lumberjack"},
            {"wolfgang", "The Strongman"},
            {"wx78", "The Soulless Automaton"},
            {"wickerbottom", "The Librarian"},
            {"wes", "The Silent"},
            {"maxwell", "The Puppet Master"},
            {"wagstaff", "The Cryptic Founder"},
            {"wathgrithr", "The Performance Artist"},
            {"webber", "The Indigestible"},
            {"walani", "The Unperturbable"},
            {"warly", "The Culinarian"},
            {"wilbur", "The Monkey King"},
            {"woodlegs", "The Pirate Captain"},
        
            {"wilba", "The Royal Adventurer"},
            {"warbucks", "The Affluent Explorer"},
            {"wormwood", "The Lonesome"},
            {"wheeler", "The Intrepid Explorer"},
        
            {"hidden", "The Unfinished"}
        };
        public static Dictionary<string, string> CHARACTER_QUOTES = new Dictionary<string, string>
        {
            {"wilson", "\"I will conquer it all with the power of my MIND!\""},
            {"willow", "\"Things are so much prettier when they burn.\""},
            {"wendy", "\"Abigail? Come back! I'm not done playing with you.\""},
            {"woodie", "\"That's a nice lookin' tree, eh?\""},
            {"wolfgang", "\"I am mighty! No one is mightier!\""},
            {"wx78", "\"EMPATHY MODULE NOT RESPONDING\""},
            {"wickerbottom", "\"Shhhh! No talking!\""},
            {"wes", "..."},
            {"maxwell", "\"Freedom!\""},
            {"wagstaff", "\"Eureka! My destiny awaits!\""},
            {"wathgrithr", "\"A test of my incredible acting!\""},
            {"webber", "\"We can overcome anything!\""},
            {"walani", "\"Forgive me if I don't get up. I don't want to.\""},
            {"warly", "\"Nothing worthwhile is ever done on an empty stomach!\""},
            {"wilbur", "\"Ooo ooa oah ah!\""},
            {"woodlegs", "\"Don't ye mind th'scurvy. Yarr-harr-harr!\""},
        
            {"wilba", "\"MAKE KINGDOM PROUD!\""},
            {"warbucks", "\"I say Ol' chap! This will be a game to remember!\""},
            {"wormwood", "\"Hello. Friend?\""},
            {"wheeler", "\"The whole world's mine to explore!\""},
        
            {"hidden", "\"Don't look at me. I'm not ready yet.\""}
        };
        public static Dictionary<string, string> CHARACTER_DESCRIPTIONS = new Dictionary<string, string>
        {
            {"wilson", "*Grows a magnificent beard"},
            {"willow", "*Immune to fire damage \n*Has a sweet lighter \n*Lights fires when nervous"},
            {"wendy", "*Is haunted by her twin sister \n*Feels comfortable in the dark \n*Doesn't hit very hard"},
            {"woodie", "*Has a lovely axe \n*And a terrible secret \n*Is thankful for bountiful harvests"},
            {"woodie_us", "*Has a lovely axe \n*And a terrible secret \n*Celebrates Thanksgiving too early"},
            {
                "woodie_canada",
                "*Has a lovely axe \n*And a terrible secret \n*Celebrates Thanksgiving at the correct time"
            },
            {"wolfgang", "*Grows stronger with a full belly \n*Is afraid of monsters and the dark"},
            {
                "wx78",
                "*Not a picky eater \n*Is charged by lightning, but damaged by water \n*Can upgrade with gears"
            },
            {"wickerbottom", "*Knows many things \n*Self-publishes books \n*Can't sleep, hates spoilage"},
            {"wes", "*Can't talk \n*Has trouble staying alive \n*Practices balloonomancy"},
            {
                "maxwell",
                "*Is dapper, but frail \n*Can split his mind into pieces \n*On a first-name basis with the night"
            },
            {"wagstaff", "*A great inventor \n*Nearsighted \n*Delicate Stomach"},
            {"wathgrithr", "*Excels in battle \n*Absorbs the power of fallen foes \n*Only eats meat"},
            {"webber", "*Is a monster \n*Can befriend spiders \n*Grows a silky smooth beard"},
            {"walani", "*Loves surfing \n*Dries off quickly \n*Is a pretty chill gal"},
            {"warly", "*Has a refined palate \n*Cooks in custom kitchenware \n*Brings a stylish chef pouch"},
            {"wilbur", "*Can't talk \n*Slow as biped, but fast as quadruped \n*Is a monkey"},
            {"woodlegs", "*Can sniff out treasure \n*Captain of the \"*Sea Legs\" \n*Pirate"},
        
            {"wilba", "*Is royalty \n*Carries her father's legacy \n*Is afraid of the dark"},
            {"warbucks", "*Is an explorer \n*Loves his fortune \n*Picky eater"},
            {"wormwood", "*Plants relate to him \n*Has a Green Thumb \n*Food fills his stomach, but not his heart"},
            {
                "wheeler",
                "Armed with an air horn \n*Has a knick knack for finding things \n*Travels lighter than most"
            },
        
            {"hidden", "*Hasn't arrived on the island yet"}
        };
    
        public class UI
        {
            public class WORLDGEN
            {
                public static string[] VERBS =
                {
                    "正在放牧",
                    "正在生成",
                    "正在召集",
                    "正在扩大",
                    "正在复制",
                    "正在暗示",
                    "正在网状划分",
                    "正在插入",
                    "正在构造",
                };
                public class NOUNS
                {
                    public static string[]
                        BASE_GAME =
                        {
                            "树木...",
                            "情感...",
                            "松树...",
                            "蜘蛛...",
                            "怪物...",
                            "强烈的绝望感...",
                            "威尔逊的胡须...",
                            "成桶的战利品...",
                            "游戏理论...",
                            "食物...",
                            "黑夜恐惧症...",
                        },
                        
                        SHIPWRECKED =
                        {
                            "丛林...",
                            "黑暗的深水...",
                            "椰树...",
                            "蛇...",
                            "海洋怪物...",
                            "强烈的被遗弃感...",
                            "威尔逊编成辫子的胡须...",
                            "成桶的金币...",
                            "多话的鹦鹉...",
                            "海产食物...",
                            "广阔的海洋...",
                            "海洋恐惧症...",
                            "漂流物...",
                            "漂浮物...",
                        },
                        
                        PORKLAND =
                        {
                            "雨林...",
                            "浓密的树叶...",
                            "昆虫...",
                            "食肉植物...",
                            "被诅咒的神庙...",
                            "由死亡定义的冒险...",
                            "鹅卵石...",
                            "商店营业时间...",
                            "街头生活...",
                            "猪丁语...",
                            "繁茂的树叶...",
                            "文明社会...",
                            "经济...",
                            "王室成员...",
                        };
                }
            }
            
            public class MAINSCREEN
            {
                public static string
                    NOTIFY = "Newsletter",
                    FORUM = "Forum",
                    BUYNOW = "Buy Now",
                    GIFT = "Send Gift",
                    MODTITLE = "Mods Installed!",
                    MODDETAIL = "Installed mods: ",
                    NEWMODDETAIL = "Newly installed mods: ",
                    NEWMODDETAIL2 = "Enable these mods from the main menu.",
                    MODDETAIL2 = "Klei is not able to help you should issues arise while using mods. Use with caution!",
                    FORCEMODDETAIL = "You are force loading these mods from modsettings.lua. They will always be enabled:",
                    OLDMODS = "The following mods are out of date and have been disabled: ",
                    FAILEDMODS = "The following mods failed to run last time and have been disabled: ",
                    OLDORFAILEDMODS = "Check the forums for updated versions.",
                    MODFAILTITLE = "WARNING!",
                    MODFAILDETAIL = "The following mod(s) have caused a failure:",
                    MODFAILDETAIL2 = "The mod will be disabled, re-enable it from the mods menu.",
                    MODQUIT = "Disable Mods",
                    MODFORUMS = "Mod Forums",
                    MODSBADTITLE = "All Mods Disabled",
                    MODSBADLOAD =
                        "The game did not start correctly last time. This was likely caused by a mod, so all mods have been disabled.\n\nYou can try re-enabling mods from the mod settings screen.",
                    MODS = "Mods",
                    ACKNOWLEDGEWARNING = "Don't Show This Again.",
                    SCRIPTERRORQUIT = "Exit Game",
                    SCRIPTERRORMODWARNING =
                        "This error may have occurred due to a mod you have enabled!\nYou have the following mods enabled:\n",
                    TESTING = "This is the testing branch!",
                    TESTINGDETAIL =
                        "You may encounter bugs or broken features, and you may lose your save game when we update. Please report all problems in the forum.",
                    TESTINGNO = "No thank-you!",
                    TESTINGYES = "I understand",
                    CONTINUE = "Continue",
                    DELETE = "Delete",
                    RESTART = "Restart",
                    NEWADVENTURE_WARN =
                        "The new adventure system is currently in active development and is provided for testing purposes. It will probably contain bugs.",
                    NEWADVENTURE = "Adventure (TEST)",
                    NEWFREEPLAY = "Sandbox",
                    NEWFREEPLAYCUSTOM = "Sandbox (Custom)",
                    NEWGAMESHORT = "Empty",
                    UNKNOWNGAME = "Unknown",
                    NEWGAMETYPE = "What kind of game would you like to play?",
                    SLOTACTION = "What would you like to do?",
                    ADVENTURE = "Adventure",
                    FREEPLAY = "Sandbox",
                    SLOT = "Game Slot",
                    SLOT_1 = "1",
                    SLOT_2 = "2",
                    SLOT_3 = "3",
                    SLOT_4 = "4",
                    IMPORT = "Import",
                    CANCEL = "Cancel",
                    SETTINGS = "Settings",
                    OPTIONS = "Options",
                    PLAYDEMO = "Play Demo",
                    ENTERPRODUCTKEY = "Enter Key",
                    ENTERKEY = "Enter New Key",
                    RESETPROFILE = "Reset profile!",
                    UNLOCKEVERYTHING = "Unlock All",
                    SURE = "Are you sure?",
                    YES = "Yes",
                    NO = "No",
                    CHEATS = "Cheats",
                    BROADCASTING = "Broadcasting",
                    PLAY = "Play!",
                    RATE = "Rate This Game",
                    ACCOUNTINFO = "Account Info",
                    VISITFORUM = "Visit Forum",
                    MOREGAMES = "More Games",
                    BUGREPORT = "Report Bug",
                    CHOOSEDIR = "Don't Starve Game Data",
                    IMPORTSUCCESS = "Success",
                    IMPORTSUCCESSDESC = "Data was imported successfully.",
                    OK = "OK",
                    IMPORTFAIL = "Failed to load",
                    GREETING = "Hi ",
                    NEWWORLD = "Create a new world!",
                    NEWWORLDDESC = "This will erase your current world and any saved games in it. Continue?",
                    RESETGAMEDESC = "This will reset your current world. Continue?",
                    NEWGAMEDESC = "This will erase your current save. Continue?",
                    ADVGAMEDESC =
                        "NOTE: This mode is still under development.\n\nFor experienced players only!\n\nYou've decided to bring the fight to Maxwell.\nCan you survive the increasingly harsh conditions he's created for you, and beat him at his own game?",
                    NEWGAME = "Start a new game!",
                    NEWGO = "Let's Go!",
                    ASKQUIT = "Do you really want to quit?",
                    ASKQUITDESC = "Maxwell will miss you!",

                    FRESHBUILD = "Fresh Build!",
                    LASTBUILDDAYS = "Last build %d days ago",
                    NEXTBUILDIMMINENT = "Next build imminent!",
                    NEXTUPDATEDAYS = "Next Update: %d days",

                    MOTDTITLE = "Klei Store",
                    MOTD = "Check out the latest items in the Klei Store!",
                    MOTDBUTTON = "Klei Store",

                    EXIT = "Exit",
                    LOGOUT = "Log Out",
                    CREDITS = "Credits",
                    UPDATENAME = "All's Well That Maxwell",
                    DLC_UPDATENAME = "Where There's a Wilson...",
                    SHIPWRECKED_UPDATENAME = "Home Sea Home.",
                    PORKLAND_UPDATENAME = "Death Defining Adventure.",
                    CONTROLS = "Controls",

                    PLAY_ON_STEAM = "PLAY ON STEAM TEXT",
                    PLAY_ON_STEAM_DETAIL = "Mods! And Stuff. It is better.",
                    LATER = "Not Now",
                    ADJUST_DISPLAY_HEADER = "Adjust Display Area.",
                    ADJUST_DISPLAY_TEXT =
                        "Parts of the game may appear outside the edges of your screen. Do you want to check and adjust your display area now? You can do this later in the settings menu.",

                    SCREECHER_DIALOG_TITLE = "Restart Required",
                    SCREECHER_DIALOG_TEXT = "The Screecher mod requires the game to be restarted.",
                    SCREECHER_NACL_DIALOG_TITLE = "The Screecher Is Waiting For You...",
                    SCREECHER_NACL_DIALOG_TEXT =
                        "The Screecher requires a Steam or Stand-alone version of Don't Starve to play.",
                    SCREECHER_NACL_OKAY = "Learn More",

                    CANT_LOAD_TITLE = "Load Failed",
                    CANT_LOAD_ROG = "Reign of Giants is not installed. Unable to load",
                    CANT_LOAD_CAPY_DLC = "Shipwrecked is not installed. Unable to load",
                    CANT_LOAD_PORKLAND_DLC = "Hamlet is not installed. Unable to load",


                    CONSOLE_EDITION_TEXT = "Console Edition",
                    ROG_UPSELL = "Buy Reign of Giants",

                    CONTROLLER_DETECTED_HEADER = "Controller Detected",
                    CONTROLLER_DETECTED_BODY =
                        "Do you want to use the controller to play Don't Starve?\n\nYou will not be asked again, but you can change this setting in the controls screen if you change your mind.",
                    ENABLECONTROLLER = "Enable Controller",
                    DISABLECONTROLLER = "Disable Controller",

                    SW_FORUMS_TITLE = "Have Feedback?",
                    SW_FORUMS_TEXT = "Want to share your thoughts?\n Join our forums!",

                    DATACOLLECTION_NOTICE = "Data Collection Notice",
                    DATACOLLECTION_BODY =
                        "We found an error in the code that caused the Data Collection setting to fail when saving.\n\nWe have fixed the problem, but if you had wanted Data Collection turned off, please reset the option by clicking the \"Disable Data\" button below.\n\nFor more details on our privacy policy and how we use the data we collect, please see our official privacy policy.",
                    DATACOLLECTION_DISABLE = "Disable Data",
                    DATACOLLECTION_CLOSE = "Close",
                    DATACOLLECTION_VIEW = "VIEW",

                    MIGRATION_TOOL = "Migration",
                    MIGRATION_DIALOG =
                        "We have detected that you have saves that need to be migrated, do you want to migrate them?",
                    MIGRATION_SUCCESSFUL_HEADER = "Success",
                    MIGRATION_SUCCESSFUL = "Migration successful",
                    MIGRATION_FAIL =
                        "We could not complete the migration because there are not enough save slots. There needs to be at least %s save slots. Please delete save(s) and run the tool again in order to migrate the saves",
                    WARNING = "WARNING",
                    MIGRATION_DIALOG_INFO =
                        "Are you sure you want to migrate the save files from the %s version to the current version?",

                    LANGUAGES = "Languages",
                    SAVEDATA = "SaveData";
            }
        
            public class CUSTOMIZATIONSCREEN
            {
                public static List<string> PRESETLEVELS = new()
                {
                    "Default",
                    "Default Plus", //-- Bootstrap the start
                    "Lights Out",
                    "Soggy", //-- Too much water - swamp etc
                    "Eternal Summer", //-- Less water, no swamp etc
                    "Winter you'll do next?", //-- Winter focus
                    "Island you an axe", //-- Island hopping
                    "Crazy Eddie", //-- Focus on sanity play
                    "Nighttime Antics", //-- Focus on nighttime play
                };

                public static List<string> PRESETLEVELDESC = new()
                {
                    "The standard Don't Starve experience",
                    "A quicker start in a harsher world.",
                    "A dark twist on the standard Don't Starve experience.",
                    "The standard Don't Starve Experience 4",
                    "The standard Don't Starve Experience 5",
                    "The standard Don't Starve Experience 6",
                    "The standard Don't Starve Experience 7",
                    "The standard Don't Starve Experience 8",
                    "The standard Don't Starve Experience 9",
                    "The standard Don't Starve Experience 10",
                };
                
                public class NAMES
                {
                    public static string
                        WORLD_SIZE = "World Size",
                        BRANCHING = "Branches",
                        LOOP = "Loops",
                        SEASON = "Seasons",
                        CAVE_ENTRANCE = "Caves", //-- World customization.
                        MARSHBUSH = "Spiky Bushes",
                        RABBITS = "Rabbit Holes",
                        MOLES = "Mole Burrows",
                        PIGS = "Pigs",
                        BEEFALOHEAT = "Beefalo Mating Frequency",
                        HUNT = "Hunts",
                        PENGUINS = "Pengulls",
                        FROGS = "Frogs",
                        TENTACLES = "Tentacles",
                        CHESS = "Clockworks",
                        LIEFS = "Treeguards",
                        SUMMER = "Summer",
                        WINTER = "Winter",
                        SPRING = "Spring",
                        AUTUMN = "Autumn",
                        FROGRAIN = "Frog Rain",
                        WILDFIRES = "Wildfires",
                        PONDS = "Ponds",
                        DECIDUOUSMONSTER = "Poison Birchnut Trees",
                        GOOSEMOOSE = "Meese/Geese",
                        MILD_SEASON = "Mild",
                        WET_SEASON = "Hurricane",
                        GREEN_SEASON = "Monsoon",
                        DRY_SEASON = "Dry",
                        SEASON_START = "Season Start",
                        TEMPERATE_SEASON = "Temperate Season",
                        HUMID_SEASON = "Humid Season",
                        LUSH_SEASON = "Lush Season",
                        DAY = "Day",
                        WEATHER = "Weather",
                        TREES = "Trees",
                        POISON = "Poison",
                        TOUCHSTONE = "Touch Stone",
                        BOONS = "Boons",
                        TIDES = "Tides",
                        FLOODS = "Floods",
                        FLOWERS = "Flowers",
                        ROCK = "Rocks",
                        MUSHROOM = "Mushrooms",
                        BIRDS = "Birds",
                        BEES = "Bees",
                        ANGRYBEES = "Killer Bees",
                        TALLBIRDS = "Tallbirds",
                        SPIDERS = "Spiders",
                        LUREPLANTS = "Meat Bulbs",
                        WHALEHUNT = "Whaling",
                        WILDBORES = "Wildbores",
                        HOUNDS = "Hounds",
                        OCEANWAVES = "Waves",
                        GLOWFLYCYCLE = "Glowfly Cycle",
                        GRASS_BUNCHES = "Tall Grass Fields",
                        FLOWERS_RAINFOREST = "Tropical Flowers",
                        DEEP_JUNGLE_FERN_NOISE = "Jungle Floor Ferns",
                        JUNGLE_BORDER_VINE = "Jungle Canopy Vines",
                        LOST_RELICS = "Lost Relics",
                        RUINED_SCULPTURES = "Ruined Sculptures",
                        SPEAR_TRAPS = "Spear Traps",
                        DART_TRAPS = "Dart Traps",
                        DOOR_VINES = "Creeping Vines",
                        RUSTED_HULKS = "Rusted Hulks",
                        ROC = "Roc",
                        ANTMAN = "Mants",
                        FOG = "Fog",
                        HAYFEVER = "Hayfever",
                        BRAMBLES = "Brambles";
                }
            }

            public class MorgueScreen
            {
                public static List<string> LEVEL_TYPE = new List<string>
                {
                    "Survival", "Rog", "Shipwrecked", "Hamlet",
                    "Caves",
                    "Adventure",
                    "Volcano",
                    "TEST",
                    "Custom",
                    "Unknown"
                };
            }
        
            public class CONTROLSSCREEN
            {
                public static List<List<string>> INPUTS = new List<List<string>>
                {
                    // KeyBoardMouse
                    [1] = new List<string>
                    {
                        // Keyboard buttons
                        [0] = "Unknown",
                        [8] = "Backspace",
                        [9] = "Tab", // KEY_TAB
                        [12] = "Clear", // KEY_CLEAR
                        [13] = "Enter", // KEY_RETURN
                        [19] = "Pause", // KEY_PAUSE
                        [27] = "Esc", // KEY_ESCAPE
                        [32] = "Space", // KEY_SPACE
                        [39] = "'", // KEY_QUOTE
                        [44] = ",", // KEY_COMMA
                        [45] = "-", // KEY_MINUS
                        [46] = ".", // KEY_PERIOD
                        [47] = "/", // KEY_SLASH
                        [48] = "0", // KEY_0
                        [49] = "1", // KEY_1
                        [50] = "2", // KEY_2
                        [51] = "3", // KEY_3
                        [52] = "4", // KEY_4
                        [53] = "5", // KEY_5
                        [54] = "6", // KEY_6
                        [55] = "7", // KEY_7
                        [56] = "8", // KEY_8
                        [57] = "9", // KEY_9
                        [59] = "Semicolon", // KEY_SEMICOLON        ;
                        [60] = "<", // KEY_LESS
                        [61] = "Equals", // KEY_EQUALS              =
                        [62] = ">", // KEY_GREATER

                        [91] = "Left Bracket", // KEY_LEFTBRACKET   [
                        [92] = "Backslash", // KEY_BACKSLASH        \\
                        [93] = "Right Bracket", // KEY_RIGHTBRACKET [
                        [96] = "`", // KEY_BACKQUOTE
                        [97] = "A", // KEY_A
                        [98] = "B", // KEY_B
                        [99] = "C", // KEY_C
                        [100] = "D", // KEY_D
                        [101] = "E", // KEY_E
                        [102] = "F", // KEY_F
                        [103] = "G", // KEY_G
                        [104] = "H", // KEY_H
                        [105] = "I", // KEY_I
                        [106] = "J", // KEY_J
                        [107] = "K", // KEY_K
                        [108] = "L", // KEY_L
                        [109] = "M", // KEY_M
                        [110] = "N", // KEY_N
                        [111] = "O", // KEY_O
                        [112] = "P", // KEY_P
                        [113] = "Q", // KEY_Q
                        [114] = "R", // KEY_R
                        [115] = "S", // KEY_S
                        [116] = "T", // KEY_T
                        [117] = "U", // KEY_U
                        [118] = "V", // KEY_V
                        [119] = "W", // KEY_W
                        [120] = "X", // KEY_X
                        [121] = "Y", // KEY_Y
                        [122] = "Z", // KEY_Z
                        [127] = "Delete", // KEY_DELETE

                        [256] = "Num 0", // KEY_KP0
                        [257] = "Num 1", // KEY_KP1
                        [258] = "Num 2", // KEY_KP2
                        [259] = "Num 3", // KEY_KP3
                        [260] = "Num 4", // KEY_KP4
                        [261] = "Num 5", // KEY_KP5
                        [262] = "Num 6", // KEY_KP6
                        [263] = "Num 7", // KEY_KP7
                        [264] = "Num 8", // KEY_KP8
                        [265] = "Num 9", // KEY_KP9
                        [266] = "Num .", // KEY_KP_PERIOD
                        [267] = "Num /", // KEY_KP_DIVIDE
                        [268] = "Num *", // KEY_KP_MULTIPLY
                        [269] = "Num -", // KEY_KP_MINUS
                        [270] = "Num +", // KEY_KP_PLUS
                        [271] = "Num Enter", // KEY_KP_ENTER

                        [273] = "Up", // KEY_UP
                        [274] = "Down", // KEY_DOWN
                        [275] = "Right", // KEY_RIGHT
                        [276] = "Left", // KEY_LEFT
                        [277] = "Insert", // KEY_INSERT
                        [278] = "Home", // KEY_HOME
                        [279] = "End", // KEY_END
                        [280] = "Page Up", // KEY_PAGEUP
                        [281] = "Page Down", // KEY_PAGEDOWN

                        [282] = "F1", // KEY_F1
                        [283] = "F2", // KEY_F2
                        [284] = "F3", // KEY_F3
                        [285] = "F4", // KEY_F4
                        [286] = "F5", // KEY_F5
                        [287] = "F6", // KEY_F6
                        [288] = "F7", // KEY_F7
                        [289] = "F8", // KEY_F8
                        [290] = "F9", // KEY_F9
                        [291] = "F10", // KEY_F10
                        [292] = "F11", // KEY_F11
                        [293] = "F12", // KEY_F12
                        [294] = "F13", // KEY_F13
                        [295] = "F14", // KEY_F14
                        [296] = "F15", // KEY_F15

                        [300] = "Num Lock", // KEY_NUMLOCK
                        [301] = "Caps Lock", // KEY_CAPSLOCK
                        [302] = "Scroll Lock", // KEY_SCROLLOCK
                        [303] = "Right Shift", // KEY_RSHIFT
                        [304] = "Left Shift", // KEY_LSHIFT
                        [305] = "Right Control", // KEY_RCTRL
                        [306] = "Left Control", // KEY_LCTRL
                        [307] = "Right Alt", // KEY_RALT
                        [308] = "Left Alt", // KEY_LALT
                        [309] = "Right Meta", // KEY_RMETA
                        [310] = "Left Meta", // KEY_LMETA
                        [311] = "Left Windows", // KEY_LSUPER       /**< Left "Windows" key */
                        [312] = "Right Windows", // KEY_RSUPER      /**< Right "Windows" key */
                        [313] = "Mode", // KEY_MODE         /**< "Alt Gr" key */
                        [314] = "Compose", // KEY_COMPOSE       /**< Multi-key compose key */

                        [315] = "Help", // KEY_HELP
                        [316] = "Print Screen", // KEY_PRINT
                        [319] = "Menu", // KEY_MENU
                        [320] = "Power", // KEY_POWER       /**< Power Macintosh power key */
                        [321] = "Euro", // KEY_EURO         /**< Some european keyboards */
                        [322] = "Undo", // KEY_UNDO         /**< Atari keyboard has Undo */

                        [400] = "Alt", // KEY_ALT
                        [401] = "Control", // KEY_CTRL
                        [402] = "Shift", // KEY_SHIFT

                        // Mouse controls
                        [1000] = "Left Mouse Button",
                        [1001] = "Right Mouse Button",
                        [1002] = "Middle Mouse Button",
                        [1003] = "Mouse Scroll Up",
                        [1004] = "Mouse Scroll Down",
                    },
                    // Xbox360
                    [2] = new List<string>
                    {
                        "\x142", //"DPad Up"
                        "\x139", //"DPad Down"
                        "\x140", //"DPad Left",
                        "\x141", //"DPad Right"
                        "\x131", //"Start",
                        "\x132", //"Back",
                        "\x133", //"Left Stick"
                        "\x136", //"Right Stick"
                        "\x134", //"Left Bumper",
                        "\x137", //"Right Bumper"
                        "\x127", //Button A",
                        "\x128", //"Button B",
                        "\x129", //"Button X",
                        "\x130", //"Button Y",

                        // Analog
                        "\x145", //"Left Thumb Left",
                        "\x146", //"Left Thumb Right",
                        "\x144", //"Left Thumb Down",
                        "\x143", //"Left Thumb Up",
                        "\x149", //"Right Thumb Left",
                        "\x150", //"Right Thumb Right",
                        "\x148", //"Right Thumb Down",
                        "\x147", //"Right Thumb Up",
                        "\x135", //"Left Trigger",
                        "\x135", //"Left Trigger",
                        "\x138", //"Right Trigger",
                        "\x138", //"Right Trigger",
                    },
                    // Generic
                    [3] = new List<string>
                    {
                        // Digital
                        "(Button %d)",

                        // Directional
                        "(DPad %d Up)",
                        "(DPad %d Down)",
                        "(DPad %d Left)",
                        "(DPad %d Right)",

                        // Analog
                        "(-X Axis)",
                        "(+X Axis)",
                        "(-Y Axis)",
                        "(+Y Axis)",
                        "(-Z Axis)",
                        "(+Z Axis)",
                        "(-X Rotation)",
                        "(+X Rotation)",
                        "(-Y Rotation)",
                        "(+Y Rotation)",
                        "(-Z Rotation)",
                        "(+Z Rotation)",
                        "(Slider 0)",
                        "(Slider 0)",
                        "(Slider 1)",
                        "(Slider 1)",
                    },
                    // PS4
                    [4] = new List<string>
                    {
                        // Digital
                        "\x224\x162\x188", //"DPad Up"	//238
                        "\x224\x162\x191", //"DPad Down"	// 241
                        "\x224\x162\x190", //"DPad Left",  //240
                        "\x224\x162\x189", //"DPad Right" //239
                        "\x224\x163\x199", //"Start",	//249
                        "\x224\x163\x198", //"Back",	//248
                        "\x224\x163\x197", //"Left Stick" //247
                        "\x224\x163\x194", //"Right Stick" //244
                        "\x224\x163\x196", //"Left Bumper", //246
                        "\x224\x163\x193", //"Right Bumper" //243
                        "\x224\x163\x203", //Button A", //253
                        "\x224\x163\x202", //"Button B", //252
                        "\x224\x163\x201", //"Button X", //251
                        "\x224\x163\x200", //"Button Y",    //250

                        // Analog
                        "\x224\x162\x185", //"Left Thumb Left", //235
                        "\x224\x162\x184", //"Left Thumb Right", //234
                        "\x224\x162\x186", //"Left Thumb Down", //236
                        "\x224\x162\x187", //"Left Thumb Up", //237
                        "\x224\x162\x181", //"Right Thumb Left", //231
                        "\x224\x162\x180", //"Right Thumb Right",//230
                        "\x224\x162\x182", //"Right Thumb Down",//232
                        "\x224\x162\x183", //"Right Thumb Up", //233
                        "\x224\x163\x195", //"Left Trigger",   //245
                        "\x224\x163\x195", //"Left Trigger",
                        "\x224\x163\x192", //"Right Trigger",   //242
                        "\x224\x163\x192", //"Right Trigger",   //242
                    },
                    // Vita Remote Play
                    [5] = new List<string>
                    {
                        // Digital
                        "\x224\x162\x188", //"DPad Up"
                        "\x224\x162\x191", //"DPad Down"
                        "\x224\x162\x190", //"DPad Left",
                        "\x224\x162\x189", //"DPad Right"
                        "\x224\x163\x199", //"Start",
                        "\x224\x163\x198", //"Back",
                        "\x224\x163\x197", //"Left Stick"
                        "\x224\x163\x194", //"Right Stick"
                        "\x224\x162\x179", //"L",
                        "\x224\x162\x178", //"R"
                        "\x224\x163\x203", //Button A",
                        "\x224\x163\x202", //"Button B",
                        "\x224\x163\x201", //"Button X",
                        "\x224\x163\x200", //"Button Y",

                        // Analog
                        "\x224\x162\x185", //"Left Thumb Left",
                        "\x224\x162\x184", //"Left Thumb Right",
                        "\x224\x162\x186", //"Left Thumb Down",
                        "\x224\x162\x187", //"Left Thumb Up",
                        "\x224\x162\x181", //"Right Thumb Left",
                        "\x224\x162\x180", //"Right Thumb Right",
                        "\x224\x162\x182", //"Right Thumb Down",
                        "\x224\x162\x183", //"Right Thumb Up",
                        "\x224\x162\x177", //"Left Trigger",
                        "\x224\x162\x177", //"Left Trigger",
                        "\x224\x162\x176", //"Right Trigger",
                        "\x224\x162\x176", //"Right Trigger",
                    },
                    // Unknown
                    [6] = new List<string>
                    {
                        "Unknown",
                        " // None selected // ",
                    },
                };
            }
            
            public class SANDBOXMENU
            {
                public static string
                    TITLE = "World Customization",
                    TITLEDETAIL = "",

                    EASY = "Not Easy",
                    MEDIUM = "Quite Difficult",
                    HARD = "Overly Taxing",

                    GENERATE = "OK",
                    MAINMENU = "Cancel",

                    CHOICEMONSTERS = "Monsters",
                    CHOICEANIMALS = "Animals",
                    CHOICERESOURCES = "Resources",
                    CHOICEFOOD = "Food",
                    CHOICECOOKED = "Prepared Food",
                    CHOICEAMTDAY = "Amount of Day",
                    CHOICEMISC = "World",

                    DAY = "Day",
                    NIGHT = "Night",
                    DUSK = "Dusk",

                    SLIDEVERYSHORT = "Very Short",
                    SLIDESHORT = "Short",
                    SLIDELONG = "Long",
                    SLIDEVERYLONG = "Very Long",
                    SLIDEALL = "Only",

                    SLIDEDEFAULT = "默认",

                    SLIDENEVER = "无",
                    SLIDEVERYRARE = "Much Less",
                    SLIDERARE = "较少",
                    SLIDEOFTEN = "较多",
                    SLIDEALWAYS = "很多",

                    SLIDEVERYSLOW = "Very Slow",
                    SLIDESLOW = "Slow",
                    SLIDEFAST = "Fast",
                    SLIDEVERYFAST = "Very Fast",

                    DEFAULT = "Autumn or Spring",
                    SUMMER = "Summer",
                    WINTER = "Winter",
                    SPRING = "Spring",
                    AUTUMN = "Autumn",
                    MILD = "Mild",
                    WET = "Hurricane",
                    GREEN = "Monsoon",
                    DRY = "Dry",
                    RANDOM = "Random",
                    BOTH = "Both",
                    ALLSEASONS = "All Seasons",
                    CLASSIC = "Autumn, Winter",
                    DLC = "Spring, Summer",
                    EXTREMETEMPS = "Summer, Winter",
                    STATICTEMPS = "Autumn, Spring",
                    EXCLUDE = "No",


                    TEMPERATE = "Temperate",
                    HUMID = "Humid",
                    LUSH = "Lush",

                    SLIDESMALL = "Default",
                    SLIDESMEDIUM = "Medium",
                    SLIDESLARGE = "Large",
                    SLIDESHUGE = "Huge",

                    SLIDEVERYSIMPLE = "Very Simple",
                    SLIDESIMPLE = "Simple",
                    SLIDECOMPLEX = "Complex",
                    SLIDEVERYCOMPLEX = "Very Complex",

                    BRANCHINGMOST = "Most",
                    BRANCHINGANY = "Default",
                    BRANCHINGLEAST = "Least",
                    BRANCHINGNEVER = "Never",

                    LOOPNEVER = "Never",
                    LOOPRANDOM = "Default",
                    LOOPALWAYS = "Always",

                    USEPRESET = "Preset";

                public static List<string>
                    CHAPTERS = new()
                    {
                        "Chapter 1 of 5",
                        "Chapter 2 of 5",
                        "Chapter 3 of 5",
                        "Chapter 4 of 5",
                        "Chapter 5 of 5",
                        "Epilogue",
                    },
                    ADVENTURELEVELS = new()
                    {
                        "A Cold Reception",
                        "The King of Winter",
                        "The Game is Afoot",
                        "Archipelago",
                        "Two Worlds",
                        "Darkness",

                        "Checkmate",
                    };
                public static string
                    NONE = "None",
                    NONEAVAILABLE = "None Available",
                    MODIFYTASKS = "Modify Tasks",

                    YES = "Yes",
                    NO = "No";
            }
        }
    
    
        public class PRETRANSLATED
        {
            public static List<string> LANGUAGES = new List<string>();
            public static List<string> LANGUAGES_TITLE = new List<string>();
            public static List<string> LANGUAGES_BODY = new List<string>();
            public static List<string> LANGUAGES_YES = new List<string>();
            public static List<string> LANGUAGES_NO = new List<string>();
        }

        public static void Init()
        {
            // Don't include this in pot generation as this file is already translated.
            if (!Main.POT_GENERATION)
            {
                StringsPreTranslated.Init();
            }
        }
    }
}