using System.Collections.Generic;
using static DYT.Constant;

namespace DYT.Map
{
    public class Terrain
    {
	    public static List<string> GROUND_NAMES = new();

	    public static Dictionary<string, Room> rooms = Rooms.rooms;
	    
	    public class TERRAIN_FILTER
	    {
		    public static List<int>
			    berrybush = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    berrybush2 = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    beefalo = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    beehive = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    wasphive = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    beemine = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    carrot_planted = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_normal = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_short = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_tall = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_sparse = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_sparse_normal = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_sparse_short = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_sparse_tall = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_burnt = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    evergreen_stump = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree_normal = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree_tall = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree_short = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree_burnt = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    deciduoustree_stump = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    livingtree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    flower = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    red_mushroom = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    green_mushroom = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    blue_mushroom = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    flint = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    fireflies = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    grass = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    depleted_grass = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    gravestone = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    firepit = new() { GROUND.ROAD },
			    log = new() { GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER },
			    mandrake = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    marsh_bush = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    marsh_tree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    pighouse = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    pigman = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    mermhouse = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    pond = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    pond_mos = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    reeds = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    rock1 = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    rock_ice = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
				    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    rock2 = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    rock_flintless = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    basalt = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    houndbone = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    houndmound = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    catcoonden = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    basalt_pillar = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    rocks = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    rabbithole = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    molehill = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    sapling = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    spiderden = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    spiderden_2 = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    spiderden_3 = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    tallbirdnest = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    tentacle = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.GRASS,
				    GROUND.FOREST, GROUND.SAVANNA, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP,
				    GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    trap_teeth = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    marbletree = new()
			    {
				    GROUND.ROAD, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },
			    marblestatue = new()
			    {
				    GROUND.ROAD, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
			    },

			    // --shipwrecked
			    ballphin = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    ballphin_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    ballphinhouse = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    bambootree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    beachresurrector = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    berrybush2_snake = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    buriedtreasure = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    bush_vine = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    snakeden = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    coralreef = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    coral_brain_rock = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    crate = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    bermudatriangle_MARKER = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    wreck = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    solofish = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    fishinhole = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    seaweed_planted = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    swordfish = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    swordfish_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    bioluminescence = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    bioluminescence_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    redbarrel = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    mussel_farm = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    lobster = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    lobsterhole = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    jellyfish_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    rainbowjellyfish_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    mangrovetree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    grass_water = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    buzzardspawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    sweet_potato_planted = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    bee = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    killerbee = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    wildborehouse = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    flup = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    flupspawner = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    flupspawner_sparse = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    flupspawner_dense = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    tidalpool = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    crabhole = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    dubloon = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    flower_evil = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    jellyfish_planted = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    rainbowjellyfish_planted = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    jungletree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    limpetrock = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    mermhouse_fisher = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    primeape = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    primeapebarrel = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    mound = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    ox = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    packim_fishbone = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    palmtree = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    poisonhole = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    sandhill = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    seashell = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    seashell_beached = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
				    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
				    GROUND.MANGROVE_SHORE
			    },
			    seagullspawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    skeleton = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    spawnpoint = new()
			    {
				    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
				    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
			    },
			    stungray = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },
			    stungray_spawner = new()
			    {
				    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
				    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
			    },

			    magmarock = new() { GROUND.ASH },
			    magmarock_gold = new() { GROUND.ASH },
			    rock_obsidian = new() { GROUND.ASH },
			    rock_charcoal = new() { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
			    dragoonden = new() { GROUND.ASH },
			    volcano_shrub = new() { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
			    elephantcactus = new() { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
			    coffeebush = new() { GROUND.VOLCANO, GROUND.VOLCANO_ROCK };

		    public static string Print(List<int> filter)
		    {
			    string val = "";
			    foreach (int i in filter) val += $" {GROUND_NAMES[i]}";
			    return val;
		    }
	    }
	    public static TERRAIN_FILTER filter = new();
	    
	    
	    static Terrain()
	    {
		    GROUND_NAMES[GROUND.IMPASSABLE] = "Impassible";
		    GROUND_NAMES[GROUND.ROAD] = "Road";
		    GROUND_NAMES[GROUND.ROCKY] = "Rocky";
		    GROUND_NAMES[GROUND.DIRT] = "Dirt";
		    GROUND_NAMES[GROUND.SAVANNA] = "Savanna";
		    GROUND_NAMES[GROUND.GRASS] = "Grass";
		    GROUND_NAMES[GROUND.FOREST] = "Forest";
		    GROUND_NAMES[GROUND.MARSH] = "Marsh";
		    GROUND_NAMES[GROUND.WOODFLOOR] = "Wood";
		    GROUND_NAMES[GROUND.CHECKER] = "Checkers";
		    GROUND_NAMES[GROUND.CARPET] = "Carpet";

		    GROUND_NAMES[GROUND.CAVE] = "CAVE";

		    GROUND_NAMES[GROUND.FUNGUS] = "FUNGUS";
		    GROUND_NAMES[GROUND.FUNGUSRED] = "FUNGUSRED";
		    GROUND_NAMES[GROUND.FUNGUSGREEN] = "FUNGUSGREEN";
		    GROUND_NAMES[GROUND.SINKHOLE] = "SINKHOLE";
		    GROUND_NAMES[GROUND.UNDERROCK] = "UNDERROCK";
		    GROUND_NAMES[GROUND.MUD] = "MUD";

		    GROUND_NAMES[GROUND.OCEAN_SHALLOW] = "OceanShallow";
		    GROUND_NAMES[GROUND.OCEAN_MEDIUM] = "OceanMedium";
		    GROUND_NAMES[GROUND.OCEAN_DEEP] = "OceanDeep";
		    GROUND_NAMES[GROUND.BEACH] = "Beach";
		    GROUND_NAMES[GROUND.JUNGLE] = "Jungle";
		    GROUND_NAMES[GROUND.SWAMP] = "Swamp";
		    GROUND_NAMES[GROUND.FLOOD] = "Flood";

		    GROUND_NAMES[GROUND.WALL_MARSH] = "WALL_MARSH";
		    GROUND_NAMES[GROUND.WALL_FUNGUS] = "WALL_FUNGUS";
		    GROUND_NAMES[GROUND.WALL_ROCKY] = "WALL_ROCKY";
		    GROUND_NAMES[GROUND.WALL_DIRT] = "WALL_DIRT";
		    GROUND_NAMES[GROUND.WALL_CAVE] = "WALL_CAVE";
		    GROUND_NAMES[GROUND.WALL_SINKHOLE] = "WALL_SINKHOLE";
		    GROUND_NAMES[GROUND.WALL_MUD] = "WALL_MUD";
		    GROUND_NAMES[GROUND.WALL_WOOD] = "WALL_WOOD";

		    GROUND_NAMES[GROUND.GROUND_NOISE] = "GROUND_NOISE";
		    GROUND_NAMES[GROUND.CAVE_NOISE] = "CAVE_NOISE";
		    GROUND_NAMES[GROUND.FUNGUS_NOISE] = "FUNGUS_NOISE";

		    // -- PORKLAND
		    GROUND_NAMES[GROUND.FIELDS] = "FIELDS";
		    GROUND_NAMES[GROUND.SUBURB] = "SUBURB";
		    GROUND_NAMES[GROUND.PIGRUINS] = "PIGRUINS";
		    GROUND_NAMES[GROUND.PIGRUINS_NOCANOPY] = "PIGRUINS_NOCANOPY";
		    GROUND_NAMES[GROUND.BATTLEGROUND] = "BATTLEGROUND";
		    GROUND_NAMES[GROUND.PLAINS] = "PLAINS";
		    GROUND_NAMES[GROUND.PAINTED] = "PAINTED";
		    GROUND_NAMES[GROUND.GASJUNGLE] = "GASJUNGLE";
		    GROUND_NAMES[GROUND.RAINFOREST] = "RAINFOREST";
		    GROUND_NAMES[GROUND.INTERIOR] = "INTERIOR";
		    GROUND_NAMES[GROUND.DEEPRAINFOREST] = "DEEPRAINFOREST";
		    GROUND_NAMES[GROUND.FOUNDATION] = "FOUNDATION";
		    GROUND_NAMES[GROUND.COBBLEROAD] = "COBBLEROAD";
		    GROUND_NAMES[GROUND.LAWN] = "LAWN";
		    GROUND_NAMES[GROUND.LILYPOND] = "LILYPOND";
		    GROUND_NAMES[GROUND.BATTLEGROUND_PLAINS_NOISE] = "BATTLEGROUND_PLAINS_NOISE";
		    GROUND_NAMES[GROUND.BATTLEGROUND_RAINFOREST_NOISE] = "BATTLEGROUND_RAINFOREST_NOISE";
	    }
    }
}