// using System.Collections.Generic;
// using static DYT.Constant;
//
// namespace DYT.Map
// {
//     public class Terrain
//     {
// 	    public static Terrain terrain = new Terrain();
// 	    
// 	    public static List<string> GROUND_NAMES = new List<string>
// 	    {
// 		    [GROUND.IMPASSABLE] = "Impassible",
// 		    [GROUND.ROAD] = "Road",
// 		    [GROUND.ROCKY] = "Rocky",
// 		    [GROUND.DIRT] = "Dirt",
// 		    [GROUND.SAVANNA] = "Savanna",
// 		    [GROUND.GRASS] = "Grass",
// 		    [GROUND.FOREST] = "Forest",
// 		    [GROUND.MARSH] = "Marsh",
// 		    [GROUND.WOODFLOOR] = "Wood",
// 		    [GROUND.CHECKER] = "Checkers",
// 		    [GROUND.CARPET] = "Carpet",
//
// 		    [GROUND.CAVE] = "CAVE",
//
// 		    [GROUND.FUNGUS] = "FUNGUS",
// 		    [GROUND.FUNGUSRED] = "FUNGUSRED",
// 		    [GROUND.FUNGUSGREEN] = "FUNGUSGREEN",
// 		    [GROUND.SINKHOLE] = "SINKHOLE",
// 		    [GROUND.UNDERROCK] = "UNDERROCK",
// 		    [GROUND.MUD] = "MUD",
//
// 		    [GROUND.OCEAN_SHALLOW] = "OceanShallow",
// 		    [GROUND.OCEAN_MEDIUM] = "OceanMedium",
// 		    [GROUND.OCEAN_DEEP] = "OceanDeep",
// 		    [GROUND.BEACH] = "Beach",
// 		    [GROUND.JUNGLE] = "Jungle",
// 		    [GROUND.SWAMP] = "Swamp",
// 		    [GROUND.FLOOD] = "Flood",
//
// 		    [GROUND.WALL_MARSH] = "WALL_MARSH",
// 		    [GROUND.WALL_FUNGUS] = "WALL_FUNGUS",
// 		    [GROUND.WALL_ROCKY] = "WALL_ROCKY",
// 		    [GROUND.WALL_DIRT] = "WALL_DIRT",
// 		    [GROUND.WALL_CAVE] = "WALL_CAVE",
// 		    [GROUND.WALL_SINKHOLE] = "WALL_SINKHOLE",
// 		    [GROUND.WALL_MUD] = "WALL_MUD",
// 		    [GROUND.WALL_WOOD] = "WALL_WOOD",
//
// 		    [GROUND.GROUND_NOISE] = "GROUND_NOISE",
// 		    [GROUND.CAVE_NOISE] = "CAVE_NOISE",
// 		    [GROUND.FUNGUS_NOISE] = "FUNGUS_NOISE",
//
// 		    //-- PORKLAND
// 		    [GROUND.FIELDS] = "FIELDS",
// 		    [GROUND.SUBURB] = "SUBURB",
// 		    [GROUND.PIGRUINS] = "PIGRUINS",
// 		    [GROUND.PIGRUINS_NOCANOPY] = "PIGRUINS_NOCANOPY",
// 		    [GROUND.BATTLEGROUND] = "BATTLEGROUND",
// 		    [GROUND.PLAINS] = "PLAINS",
// 		    [GROUND.PAINTED] = "PAINTED",
// 		    [GROUND.GASJUNGLE] = "GASJUNGLE",
// 		    [GROUND.RAINFOREST] = "RAINFOREST",
// 		    [GROUND.INTERIOR] = "INTERIOR",
// 		    [GROUND.DEEPRAINFOREST] = "DEEPRAINFOREST",
// 		    [GROUND.FOUNDATION] = "FOUNDATION",
// 		    [GROUND.COBBLEROAD] = "COBBLEROAD",
// 		    [GROUND.LAWN] = "LAWN",
// 		    [GROUND.LILYPOND] = "LILYPOND",
// 		    [GROUND.BATTLEGROUND_PLAINS_NOISE] = "BATTLEGROUND_PLAINS_NOISE",
// 		    [GROUND.BATTLEGROUND_RAINFOREST_NOISE] = "BATTLEGROUND_RAINFOREST_NOISE",
// 	    };
//
// 	    public Dictionary<string, Room> rooms = Rooms.rooms;
// 	    
// 	    //-- These items will not spawn on a terrain tile of the types in the list provided
// 	    private readonly Dictionary<string, List<int>> TERRAIN_FILTER = new Dictionary<string, List<int>>
// 	    {
// 		    ["berrybush"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["berrybush2"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["beefalo"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["beehive"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["wasphive"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["beemine"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["carrot_planted"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_normal"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_short"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_tall"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_sparse"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_sparse_normal"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_sparse_short"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_sparse_tall"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_burnt"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["evergreen_stump"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree_normal"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree_tall"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree_short"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree_burnt"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["deciduoustree_stump"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["livingtree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.DIRT,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.BEACH, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["flower"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["red_mushroom"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["green_mushroom"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["blue_mushroom"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flint"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["fireflies"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["grass"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["depleted_grass"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["gravestone"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["firepit"] = new List<int> { GROUND.ROAD },
// 		    ["log"] = new List<int> { GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER },
// 		    ["mandrake"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["marsh_bush"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["marsh_tree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["pighouse"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["pigman"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["mermhouse"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["pond"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["pond_mos"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["reeds"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["rock1"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["rock_ice"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE, GROUND.JUNGLE, GROUND.BEACH, GROUND.SWAMP, GROUND.BEACH,
// 			    GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["rock2"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["rock_flintless"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["basalt"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["houndbone"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["houndmound"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["catcoonden"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["basalt_pillar"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["rocks"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["rabbithole"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["molehill"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["sapling"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.MARSH,
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["spiderden"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["spiderden_2"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["spiderden_3"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["tallbirdnest"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["tentacle"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.ROCKY, GROUND.GRASS,
// 			    GROUND.FOREST, GROUND.SAVANNA, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP,
// 			    GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["trap_teeth"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["marbletree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["marblestatue"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE, GROUND.MANGROVE_SHORE
// 		    },
//
// 		    // --shipwrecked
// 		    ["ballphin"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["ballphin_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["ballphinhouse"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["bambootree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["beachresurrector"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["berrybush2_snake"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["buriedtreasure"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["bush_vine"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["snakeden"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["coralreef"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["coral_brain_rock"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["crate"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["bermudatriangle_MARKER"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["wreck"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["solofish"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["fishinhole"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["seaweed_planted"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["swordfish"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["swordfish_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["bioluminescence"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["bioluminescence_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["redbarrel"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["mussel_farm"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["lobster"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["lobsterhole"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["jellyfish_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["rainbowjellyfish_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["mangrovetree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["grass_water"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["buzzardspawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["sweet_potato_planted"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["bee"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["killerbee"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["wildborehouse"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flup"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flupspawner"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flupspawner_sparse"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flupspawner_dense"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["tidalpool"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["crabhole"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["dubloon"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["flower_evil"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["jellyfish_planted"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["rainbowjellyfish_planted"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["jungletree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["limpetrock"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["mermhouse_fisher"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["primeape"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["primeapebarrel"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["mound"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["ox"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["packim_fishbone"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["palmtree"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["poisonhole"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["sandhill"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["seashell"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["seashell_beached"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.OCEAN_SHALLOW,
// 			    GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE, GROUND.OCEAN_CORAL_SHORE,
// 			    GROUND.MANGROVE_SHORE
// 		    },
// 		    ["seagullspawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["skeleton"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["spawnpoint"] = new List<int>
// 		    {
// 			    GROUND.OCEAN_SHALLOW, GROUND.OCEAN_MEDIUM, GROUND.OCEAN_DEEP, GROUND.OCEAN_SHORE,
// 			    GROUND.OCEAN_CORAL_SHORE, GROUND.MANGROVE_SHORE
// 		    },
// 		    ["stungray"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
// 		    ["stungray_spawner"] = new List<int>
// 		    {
// 			    GROUND.ROAD, GROUND.WOODFLOOR, GROUND.CARPET, GROUND.CHECKER, GROUND.JUNGLE, GROUND.BEACH,
// 			    GROUND.SWAMP, GROUND.SAVANNA, GROUND.ROCKY, GROUND.MEADOW, GROUND.MAGMAFIELD, GROUND.TIDALMARSH
// 		    },
//
// 		    ["magmarock"] = new List<int> { GROUND.ASH },
// 		    ["magmarock_gold"] = new List<int> { GROUND.ASH },
// 		    ["rock_obsidian"] = new List<int> { GROUND.ASH },
// 		    ["rock_charcoal"] = new List<int> { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
// 		    ["dragoonden"] = new List<int> { GROUND.ASH },
// 		    ["volcano_shrub"] = new List<int> { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
// 		    ["elephantcactus"] = new List<int> { GROUND.VOLCANO, GROUND.VOLCANO_ROCK },
// 		    ["coffeebush"] = new List<int> { GROUND.VOLCANO, GROUND.VOLCANO_ROCK }
// 	    };
// 	    public readonly Dictionary<string, List<int>> filter;
//
// 	    private Terrain()
// 	    {
// 		    filter = TERRAIN_FILTER;
// 	    }
//     }
// }